### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by tehw0lf** [tehw0lf/paw#1]
As far as I tested it, all switches were working, but if someone would like to add a test command (-t or -T) that tests all functionalities, I would greatly appreciate the help :)

**Comment by XFabian** [comment]
I would like to work on this

**Comment by tehw0lf** [comment]
Yay, feel free to do so!

**Comment by tehw0lf** [comment]
Issue closed, thank you very much for the contribution! I will look into the bug you mentioned as soon as I can!
