### ISSUE TITLE
`self` should be for keeping state, not as temp variables

### ISSUE THREAD

**Issue by Spindel** [tehw0lf/paw#7]
https://github.com/tehw0lf/paw/blob/37cd6f1a81463507e56294179c5d8f4a5c321654/paw.py#L260

`self.report` is set to a message, and then never used again.  Just drop it from `self` and set the variable `report` and print it, or print without storing in an variable.

**Comment by tehw0lf** [comment]
Thanks, I went with the second option, printing without storing the string in a variable beforehand.
