### ISSUE TITLE
__init__ should document all the state of the class

### ISSUE THREAD

**Issue by Spindel** [tehw0lf/paw#8]
https://github.com/tehw0lf/paw/blob/37cd6f1a81463507e56294179c5d8f4a5c321654/paw.py#L280

The __init__ function doesn't document all the required state of the class instance.

most notable:
`self.args`
`self.parser`

**Comment by tehw0lf** [comment]
I migrated parse_args() out of the class as you suggested in #6 - thus this issue got passively resolved as well.

**Comment by Spindel** [comment]
Cheers! 
( Good job on them, and good job on the commit messages relating )
